<TABLE>
<TR>
<TD>
&nbsp;
</TD>
</TR>
</TABLE>

<TABLE>
<TR>
<TD>
<!--agorascript-pre
if ($sc_qty_box_on_cart_display =~ /yes/i) {
  return '<INPUT TYPE="IMAGE" NAME="submit_change_quantity_button" VALUE="Change Quantity" SRC="%%URLofImages%%/edit_items.gif" BORDER="0">';
 } else {
  return '<INPUT TYPE="IMAGE" NAME="change_quantity_button" VALUE="Change Quantity" SRC="%%URLofImages%%/edit_items.gif" BORDER="0">';
 }
-->
<INPUT TYPE="IMAGE" NAME="delete_item_button" VALUE="Delete Items" SRC="%%URLofImages%%/remove_items.gif" BORDER="0">
<INPUT TYPE="IMAGE" NAME="continue_shopping_button" VALUE="Continue Shopping" SRC="%%URLofImages%%/continue_shopping.gif" BORDER="0">
</TD>
</TR>
</TABLE>

<!--DO NOT DELETE THIS NEXT LINE-->
%%offlineSecureURL%%
<!--END DO NOT DELETE THIS NEXT LINE-->

<TABLE>
<TR>

<TD>
<INPUT TYPE="IMAGE" NAME="order_form_button" VALUE="Complete Secure Order" SRC="%%URLofImages%%/complete_order.gif" BORDER="0">

</TD>

</TR>
</TABLE>

</FORM>

</CENTER>
