<TR> 
<TD COLSPAN = "3"><HR></TD>
</TR>
<TR WIDTH="550"> 
<td>
 <table width=100% cellpadding=0 cellspacing=0 border=0>
 <tr>  
  <TD COLSPAN=1 align=rleft>
  <b>%%name%%</b> <font color="#FF0000">(%%price%%)</font></td>
  <TD COLSPAN=2 align=right>
  <A HREF="%%scripturl%%?cart_id=&p_id=%%ProductID%%&xm=on&ppinc=search2">
  <FONT FACE=ARIAL>Display</FONT></A>
  &nbsp;&nbsp;&nbsp;
  <A HREF="%%scripturl%%?cart_id=&p=%%CategoryID%%&xm=on">
  <FONT FACE=ARIAL>Show Similar</FONT></A></TD>
 </tr>
 </table></td>
</TR>
