</form>
</TD></TR><tr><td colspan=3 valign=top>
<TABLE WIDTH=100% BORDER=0 cellspacing=0 cellpadding=0 bgcolor="#cccccc" background="agora.cgi?secpicserve=steelgrey.jpg" align=top><TR valign=top>
<TD>
<CENTER>
<!--agorascript-pre 
&capture_STDOUT; 
&cartlinks;
  print "<font face=\"Arial\" size=\"2\">";
# take make links underlined
# $cartlinks =~ s/style=\"text-decoration: none\"//ig;
# to layout horizontally with 3 spaces
# $cartlinks =~ s/<br>/&nbsp;&nbsp;&nbsp;/ig;
# to layout horizontally with | dividers spaces
$cartlinks =~ s/<br>/&nbsp;&nbsp;|&nbsp;&nbsp;/ig;
print $cartlinks;
  print "</font>";
&uncapture_STDOUT;  --></CENTER></TD></TR></TABLE>
</td></tr></TABLE>
</td></tr>
</TABLE>
</td></tr>
</table><CENTER>
<TABLE WIDTH=550 BORDER=0><TR WIDTH=500 BORDER=0>
<TD WIDTH=550 BORDER=0 ALIGN=CENTER><CENTER><BR>
<small>Copyright 1999-2003 K-Factor Technologies Inc. at <a href="http://www.agoracart.com">AgoraCart.com</a></small></CENTER></TD></TR></TABLE></CENTER>
